name: Deploy to Appwrite
on:
  push:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Init Appwrite CLI
        uses: appwrite/setup-for-actions@v1
        with:
          endpoint: 'https://api.gettooru.com/v1'
          project: '6193ae37b6810'
          key: '${{ secrets.APPWRITE_API_KEY }}'
      - name: Deploy my function to Appwrite
        run: |
            appwrite functions createTag \
              --functionId='619610d5d2bbe' \
              --command="node dist/index.js" \
              --code="./" 
